"""app_preferences table added

Revision ID: 07d5e7dca897
Revises: 8e67151d6178
Create Date: 2024-08-22 22:54:38.768578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07d5e7dca897'
down_revision: Union[str, None] = '8e67151d6178'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('version_str', sa.String(), nullable=False),
    sa.Column('latest_version', sa.Integer(), nullable=False),
    sa.Column('min_supported_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_preferences')
    # ### end Alembic commands ###
