"""transaction id set to nullable

Revision ID: 2242a744a0e8
Revises: f903076cc194
Create Date: 2024-07-28 19:52:16.993792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2242a744a0e8'
down_revision: Union[str, None] = 'f903076cc194'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'transction_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'transction_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
