"""changes in refferal and user_bids table

Revision ID: 8e67151d6178
Revises: 60b8dcd39364
Create Date: 2024-08-22 22:13:52.206445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e67151d6178'
down_revision: Union[str, None] = '60b8dcd39364'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('commission', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('user_bids', sa.Column('win_amount', sa.Integer(), nullable=True))
    op.drop_index('ix_user_bids_bid_size', table_name='user_bids')
    op.drop_column('user_bids', 'bid_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_bids', sa.Column('bid_size', postgresql.ENUM('big', 'small', name='bidsizeoptions'), autoincrement=False, nullable=True))
    op.create_index('ix_user_bids_bid_size', 'user_bids', ['bid_size'], unique=False)
    op.drop_column('user_bids', 'win_amount')
    op.drop_column('transactions', 'commission')
    # ### end Alembic commands ###
