"""bid_size column added in user_bids

Revision ID: ab3456dc82c9
Revises: 07d5e7dca897
Create Date: 2024-08-23 00:57:52.817138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab3456dc82c9'
down_revision: Union[str, None] = '07d5e7dca897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_bids', sa.Column('bid_size', sa.Enum('big', 'small', name='bidsizeoptions'), nullable=True))
    op.create_index(op.f('ix_user_bids_bid_size'), 'user_bids', ['bid_size'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_bids_bid_size'), table_name='user_bids')
    op.drop_column('user_bids', 'bid_size')
    # ### end Alembic commands ###
