"""initial tables added

Revision ID: abb7f83a8a90
Revises: 
Create Date: 2024-07-06 22:21:54.217643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abb7f83a8a90'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('Now()'), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('otp', sa.String(), nullable=False),
    sa.Column('otp_type', sa.String(), nullable=False),
    sa.Column('is_used', sa.Boolean(), server_default=sa.text('False'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temp_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('Now()'), nullable=False),
    sa.Column('role', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.Column('verified', sa.Boolean(), server_default=sa.text('False'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temp_users_phone_number'), 'temp_users', ['phone_number'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone_no', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('Now()'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('True'), nullable=False),
    sa.Column('role', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('refferal', sa.String(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('last_login', sa.TIMESTAMP(timezone=True), server_default=sa.text('Now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('False'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_no')
    )
    op.create_table('coins',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('num_of_coins', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('coin_type', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('multiplication_factor', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('Now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('refferals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('refferal_user_id', sa.Integer(), nullable=True),
    sa.Column('reffered_user_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), server_default=sa.text('10'), nullable=False),
    sa.Column('is_success', sa.Boolean(), server_default=sa.text('True'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('Now()'), nullable=False),
    sa.ForeignKeyConstraint(['reffered_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refferals')
    op.drop_table('coins')
    op.drop_table('users')
    op.drop_index(op.f('ix_temp_users_phone_number'), table_name='temp_users')
    op.drop_table('temp_users')
    op.drop_table('otp')
    # ### end Alembic commands ###
