"""game_logs and user_bids tables added

Revision ID: be9a8a2e88ba
Revises: abb7f83a8a90
Create Date: 2024-07-07 22:10:15.635561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be9a8a2e88ba'
down_revision: Union[str, None] = 'abb7f83a8a90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_type', sa.Integer(), nullable=False),
    sa.Column('result_number', sa.Integer(), nullable=True),
    sa.Column('result_color', sa.Enum('red', 'green', 'violet', 'green_violet', 'red_violet', name='bidcoloroptions'), nullable=True),
    sa.Column('result_size', sa.Enum('big', 'small', name='bidsizeoptions'), nullable=True),
    sa.Column('is_finished', sa.Boolean(), server_default=sa.text('False'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('Now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_logs_game_type'), 'game_logs', ['game_type'], unique=False)
    op.create_index(op.f('ix_game_logs_result_color'), 'game_logs', ['result_color'], unique=False)
    op.create_index(op.f('ix_game_logs_result_number'), 'game_logs', ['result_number'], unique=False)
    op.create_index(op.f('ix_game_logs_result_size'), 'game_logs', ['result_size'], unique=False)
    op.create_table('user_bids',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_coin_price', sa.Integer(), server_default=sa.text('10'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('bid_number', sa.Integer(), nullable=True),
    sa.Column('bid_color', sa.Enum('red', 'green', 'violet', 'green_violet', 'red_violet', name='bidcoloroptions'), nullable=True),
    sa.Column('bid_size', sa.Enum('big', 'small', name='bidsizeoptions'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('Now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game_logs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_bids_bid_color'), 'user_bids', ['bid_color'], unique=False)
    op.create_index(op.f('ix_user_bids_bid_number'), 'user_bids', ['bid_number'], unique=False)
    op.create_index(op.f('ix_user_bids_bid_size'), 'user_bids', ['bid_size'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_bids_bid_size'), table_name='user_bids')
    op.drop_index(op.f('ix_user_bids_bid_number'), table_name='user_bids')
    op.drop_index(op.f('ix_user_bids_bid_color'), table_name='user_bids')
    op.drop_table('user_bids')
    op.drop_index(op.f('ix_game_logs_result_size'), table_name='game_logs')
    op.drop_index(op.f('ix_game_logs_result_number'), table_name='game_logs')
    op.drop_index(op.f('ix_game_logs_result_color'), table_name='game_logs')
    op.drop_index(op.f('ix_game_logs_game_type'), table_name='game_logs')
    op.drop_table('game_logs')
    # ### end Alembic commands ###
