"""transactions table added

Revision ID: f903076cc194
Revises: a8754ff28c50
Create Date: 2024-07-20 01:32:36.193400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f903076cc194'
down_revision: Union[str, None] = 'a8754ff28c50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('transction_id', sa.String(), nullable=False),
    sa.Column('is_added', sa.Boolean(), server_default=sa.text('True'), nullable=False),
    sa.Column('transaction_medium', sa.String(), nullable=True),
    sa.Column('receiver_details', sa.String(), nullable=True),
    sa.Column('screenshot_url', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('False'), nullable=False),
    sa.Column('is_rejected', sa.Boolean(), server_default=sa.text('False'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('Now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transction_id')
    )
    op.create_unique_constraint(None, 'users', ['refferal'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_table('transactions')
    # ### end Alembic commands ###
